### ISSUE TITLE
Date is not parsed correctly during setting variable value

### ISSUE THREAD

**Issue by clarkfinger** [EliteAPI/EliteVA#1]
Due to fact that date is parsed with pattern "d-M-yyyy HH:mm:ss" it will work only for OS that are using such a format.

Possible solution is to replace 
_proxy.Variables.Set(variable.Name,
                            DateTime.ParseExact(variable.Value.ToString(), "d-M-yyyy HH:mm:ss",
                                CultureInfo.InvariantCulture));
with
_proxy.Variables.Set(variable.Name,
                            DateTime.Parse(variable.Value.ToString()));

File: EliteVA.VoiceAttackPlugin.cs https://github.com/EliteAPI/EliteVA/blob/main/EliteVA/VoiceAttackPlugin.cs

**Comment by Somfic** [comment]
Thanks! The change is implemented in v0.2.4.

**Comment by clarkfinger** [comment]
Shure, there is one more issue I am facing. I haven't found a solution for it yet. I have sent you an e-mail about it as I am not sure if this is foult of EliteVA, EliteAPI or VoiceAttack.
